### ISSUE TITLE
AlignByKey - '{' stopped working

### ISSUE THREAD

**Issue by JamesWatton** [cpmcgrath/codealignment#50]
Hi,

Previously up until today I would highlight a bunch of properties in a C# file, press Ctrl+Shift+= to 'Align By Key' and then press '{' to align them as follows:

```

public bool Failed              { get; private set; }
public string FailureMessage    { get; private set; }
public string ExceptionInfo     { get; private set; }
public string ErrorInfo         { get; private set; }
```

This morning this appears to no longer work. I get the "Waiting for second key chord.." pop up (which I'm sure I never saw before..) and pressing the '{' key does nothing. It works if I align by equals, or AlignBykey and then '=', and I can't see any updates or anything newly installed in VS2013 that would have broken this.

Any thoughts? It's very frustrating as using this extension has been wonderful and is now more of a habit than anything.

**Comment by cpmcgrath** [comment]
Hi,
There should be two shortcuts set for Code Alignment...
**Edit.AlignByKey** which by default is set to Ctrl =
and
**Edit.AlignByString** which by default is set to Ctrl Shift =
From the sound of it your setup has been modified so that either Align By String is no longer set to the shortcut or another shortcut is overriding it.

Check for these things in Visual Studio's Options > Environment > Keyboard and it should resolve the problem for you.

**Comment by JamesWatton** [comment]
Ah yes! I completely overlooked the "AlignByString" shortcut when I was checking the assigned keys. That has indeed resolved it, thank you!

And thanks again on a great extension!
