### ISSUE TITLE
Extension for SSMS

### ISSUE THREAD

**Issue by mgrishkov** [cpmcgrath/codealignment#68]
Dear team, you've made an amazing tool for VS and other editors. Unfortunately you totally forgot about SSMS (however like MS do). T-Sql developers have to copy-paste code between editors to align code (for example to align insert statements by comma) or use editors with limited functuionality (like SSDT).
Do you suppose to create extension for SSMS?

**Comment by cpmcgrath** [comment]
Hi,
Thanks for the kind words. 
I have tried in the past, but
* Officially SSMS doesn't support extensions which makes finding the documentation really hard.
* I doubt I'd be able to have a great deployment model.
* Without reading too much between the lines... There's not much of a future for SSMS

But on the positive side, there's SQL Operations Studio - https://github.com/Microsoft/sqlopsstudio - it's still in preview, but this is clearly meant to be a replacement for SSMS.
I haven't looked into it too much yet, but I'm pretty sure I can get the visual studio code port working on it with very little effort.

I'm actually really excited about SQL Operations Studio so I'll probably port Code Alignment to it sooner rather than later.
