### ISSUE TITLE
If the user uses tabs, still give them the option to align with only spaces

### ISSUE THREAD

**Issue by cpmcgrath** [cpmcgrath/codealignment#9]
Tabs should be for indenting, not aligning.
So this should be the default behaviour with an option to use tabs.

**Comment by Acecool** [comment]
Tabs should be used for aligning because 1 character vs 4/5 over 10s of thousands of lines will increase file-size. And, using this plugin to 13961 lines won't allow me to use my save macro ( which converts 5 spaces to tab, 4 spaces to tab, 3 spaces to tab, 2 spaces to tab, and trim trailing white-space  )... This file is 690kb using tab indents. Using space indents from this plugin made the file 1,731KB... Over 1.1mb of just SPACES which is stupid.

**Comment by cpmcgrath** [comment]
Hi Acecool,
In Code Alignment options (from align by string click the cog) you can tick "Use IDE tab settings for alignment" to enable tabs (if the IDE settings also says that the tab key inserts tabs not spaces)
Prior to the commit you mentioned if your IDE settings inserted tabs then you were forced to insert tabs in alignments. As spaces are better for alignments (see https://github.com/cpmcgrath/codealignment/wiki/Tabs-&-Alignment ) This issue said that if your IDE has that setting on, you should still have the option to use spaces, and that should be the default.

As for your file size. I would still say the size increase is insignificant. In terms of storage a MB on a TB drive is nothing. For transport, if you really were concerned about size you'd use compression (which would barely make the file size different) or if it was code you could minify it.
